-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 11:19:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `academia`;
CREATE SCHEMA IF NOT EXISTS academia DEFAULT CHARACTER SET utf8 ;
USE academia ;

-- -----------------------------------------------------
-- Table academia.funcionario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS academia.funcionario (
  id_pessoa VARCHAR(45) NOT NULL,
  cargo VARCHAR(45) NOT NULL,
  nome VARCHAR(45) NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  telefone VARCHAR(45) NULL,
  PRIMARY KEY (id_pessoa))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table academia.cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS academia.cliente (
  id_cliente INT NOT NULL AUTO_INCREMENT,
  plano VARCHAR(45) NOT NULL,
  nome VARCHAR(45) NOT NULL,
  cpf VARCHAR(45) NOT NULL,
  telefone VARCHAR(45) NULL,
  PRIMARY KEY (id_cliente))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table academia.aulas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS academia.aulas (
  id_exercicio VARCHAR(11) NOT NULL,
  modalidade VARCHAR(45) NULL,
  turno VARCHAR(45) NULL,
  funcionario_id_pessoa VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_exercicio, funcionario_id_pessoa),
  INDEX fk_aulas_funcionario1_idx (funcionario_id_pessoa ASC) VISIBLE,
  CONSTRAINT fk_aulas_funcionario1
    FOREIGN KEY (funcionario_id_pessoa)
    REFERENCES academia.funcionario (id_pessoa)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table academia.aula_cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS academia.aula_cliente (
  fk_aula VARCHAR(11) NOT NULL,
  fk_cliente INT NOT NULL,
  PRIMARY KEY (fk_aula, fk_cliente),
  INDEX fk_aulas_has_tb_cliente_tb_cliente1_idx (fk_cliente ASC) VISIBLE,
  INDEX fk_aulas_has_tb_cliente_aulas1_idx (fk_aula ASC) VISIBLE,
  CONSTRAINT fk_aulas_has_tb_cliente_aulas1
    FOREIGN KEY (fk_aula)
    REFERENCES academia.aulas (id_exercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_aulas_has_tb_cliente_tb_cliente1
    FOREIGN KEY (fk_cliente)
    REFERENCES academia.cliente (id_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table academia.historico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS academia.historico (
  id INT NOT NULL,
  data DATE NULL,
  descricao VARCHAR(45) NULL,
  fk_cliente INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_historico_cliente1_idx (fk_cliente ASC) VISIBLE,
  CONSTRAINT fk_historico_cliente1
    FOREIGN KEY (fk_cliente)
    REFERENCES academia.cliente (id_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;